### ISSUE TITLE
a few questions, if you don't mind. (about configuration)

### ISSUE THREAD

**Issue by zeffii** [nikhilsinghmus/CsoundST3#1]
first of all, thanks for this plugin, it worked immediately.

i would like to execute python from the csd file, and can't figure out where to configure the python 2.4 path for csound to use. I assume it's 2.4 because that's all i can find for csound-python topics.

any help appreciated.

**Comment by nikhilsinghmus** [comment]
Hi @zeffii, you should be able to use 2.7 (see the relevant FLOSS manual [chapter](http://floss.booktype.pro/csound/b-python-inside-csound/)). In case the installer isn't finding your Python installation, you could likely build from source and configure it directly (see [here](https://github.com/csound/csound/blob/a5b56e6bb9362e26d3dec6fb96545afc6c3ba850/CMakeLists.txt#L212)). You could also ask the Csound mailing [list](http://csound.1045644.n5.nabble.com/Csound-General-f1093014.html), they likely have more current information than me.

**Comment by zeffii** [comment]
perfect @nikhilsinghmus !  ok, thankyou for your time!  py2.7.8 is an improvement :)

**Comment by zeffii** [comment]
OK i've added stuff to windows environment variables

![image](https://user-images.githubusercontent.com/619340/96369564-1f508980-115b-11eb-8c7f-0f93c5d200bd.png)

and now! 

![image](https://user-images.githubusercontent.com/619340/96369532-dc8eb180-115a-11eb-89fd-106a600ccd56.png)

let's see how this thing roks.

---- for anyone else reading this

if you see a printout with something like this "ImportError: No module named Site" , then ofcourse python was found because that's what's printing the error.  So it's similar to this https://stackoverflow.com/a/8895513/1243487
